# Generated by Django 4.1.2 on 2022-10-27 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_rename_artist_id_song_artistid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artistid',
            new_name='artist_id',
        ),
        migrations.AlterField(
            model_name='song',
            name='date_realeased',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
