# Generated by Django 4.1.2 on 2022-10-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_remove_song_id_alter_song_artist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist_id',
            field=models.IntegerField(db_column='artist_id', primary_key=True, serialize=False),
        ),
    ]
