# Generated by Django 4.1.2 on 2022-10-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0005_alter_song_artist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lyrics',
            name='song_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist_id',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='date_realeased',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='number_of_likes',
            field=models.IntegerField(null=True),
        ),
    ]
