# Generated by Django 4.1.2 on 2022-10-28 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_song_id_alter_artist_age_alter_lyrics_song_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Lyrics',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
