# Generated by Django 4.1.2 on 2022-10-28 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0008_song_lyrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
    ]
