# Generated by Django 4.1.2 on 2022-10-28 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0009_remove_song_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_parent', to='musicapp.song'),
        ),
    ]
